### ISSUE TITLE
Naming Conventions for Toolboxes

### ISSUE THREAD

**Issue by versionbaygt** [mathworks/toolboxdesign#22]
It might be good to call out MathWorks guidelines in naming toolboxes

- MATLAB for XYZ vs XYZ with MATLAB?
- requirements that the File Exchange Team looks at that historically have meant that someone had to a later stage change something

**Comment by rpurser47** [comment]
Hi.  Loved the post on the MATLAB Jokes toolbox.  The lawyers have taught me that, generally speaking, if you want to use MATLAB (or any trademarked name) in the name of something you create, you should put it at the end so that it's clear that you are not claiming the trademarked thing. So, "Jokes for MATLAB" or "Jokes Toolbox for MATLAB"

So, the recommended pattern if you want to use MATLAB in the name of your toolbox is "<your thing> for MATLAB" or "<your thing Toolbox for MATLAB"

I'm on the fence on whether to put this advice in the best practice, but I'll consider it for a future version.
